[build]
  command = "yarn functions:install && yarn build"
  functions = "built-netlify-functions"
  publish = "public/"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
[[redirects]]
  from = "/zoom"
  to = "https://fuhsd-org.zoom.us/j/98614836312?pwd=Q3B4bkovSHk5ZlB4MGFjWTFJcW9RUT09"
  force = true # ensure that we always redirect
[[redirects]]
  from = "/join"
  to = "https://mailchi.mp/9caf71779f11/mvmun22-23"
  force = true # ensure that we always redirect
